name: Node Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -yq install libpq-dev postgresql-client-13

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Prepare Schemas
        run: |
          psql < db/globals.sql
          psql -1 tracking < db/schema/*
        env:
          PGDATABASE: postgres_db
          PGPASSWORD: postgres_password
          PGUSER: postgres_user
          PGHOST: localhost

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}

      - name: Installation & Tests
        run: |
          npm ci
          npm test
        env:
          NODE_ENV: production
          PGDATABASE: "tracking"
          PGUSER: "tracking-worker"
          PGPASSWORD: "tracking-password"
          PGHOST: localhost

